server:
  port: 9090

# application.properties
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: templates/
    suffix: .html
    check-template-location: true
    enabled: true
    cache: false
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: qwer

  logging:
  level:
    root: debug

